PR for review of the milestone 3
kalavhan/facebook-clone pull request #4
Opened 2020-01-31 16:50 UTC by kalavhan

Devise behavior modified to accomplish the desired result :
- Signup and login in the same pages as Facebook has it
     + This required to modify the actions in the devise controller
     + The login form is a partial that we render in the header conditionally if no user has signed in
     + The user is redirected to Signup page if he is not signed in

2020-01-31 20:05 UTC, samgaco requested changes
Hi @kalavhan and @fegzycole :high_brightness: 

Everything looking right! just one thing to correct. We should have a users controller and a index of all the users.

Work on that and submit back for another review. Good spirit! :muscle: 
--------------------

* ###### STATUS OF THE PROJECT: REQUESTED CHANGES :stop_sign:

2020-01-31 20:05 UTC, samgaco commented on app/controllers/posts_controller.rb
> +class PostsController < ApplicationController
- [x] There should be also a controller for the user displaying all the users, with a page to show a list of all available users. [Requirement](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone3/userctr.png).

2020-01-31 20:05 UTC, samgaco commented on app/controllers/posts_controller.rb
> +    @posts = Post.where(user_id: current_user.id)
- [ ] SUGGESTION Have into account that everything connected with data processing should be encapsulated in models and used in controllers.

2020-02-01 04:19 UTC, Ispirett approved these changes
## Status Approved :+1: :100: 
Great job @kalavhan  @fegzycole  you have done well move  along. :+1:

2020-02-01 07:06 UTC, merged